---
- hosts: all
  become: yes
  tasks:
 
    - name: Install Python3
      apt: name=python3 update_cache=yes state=latest

    - name: Install jupyter
      apt: name=jupyter-console update_cache=yes state=latest

    - name: Install tensorflox
      apt: name=tensorflow update_cache=yes state=latest
        
      
      
