---
- hosts: all
  become: yes
  tasks:
 
    - name: Install Python3
      apt: name=python3 update_cache=yes state=latest

      - name: Install jupyter
      pip:
        name: jupyter-console==5.0
        virtualenv_python: python2.7

      - name: Install notebook
      pip:
        name: notebook==4.2.1
        virtualenv_python: python2.7
      
      
