---
- hosts: all
  become: yes
  tasks:
 
    - name: Install Python3
      apt: name=python3 update_cache=yes state=latest

    - name: install pip3
      apt: name=python3-pip state=present 

    - name: Install jupyter
      ansible.builtin.pip:
        name: notebook
    
    - name: Install tensorflow
      ansible.builtin.pip:
        name: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.6.0-cp39-cp39-manylinux2010_x86_64.whl
        extra_args: --no-cache-dir

  
      
      
